title: 'Diakov Portfolio'
default_lang: en
author:
  name: 'Joe Bloggs'
  email: joe@example.com
taxonomies:
  - category
  - tag
metadata:
  description: 'laravel, php, web-dev'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects: null
routes: null
blog:
  route: /blog
